### ISSUE TITLE
Problems with official website?

### ISSUE THREAD

**Issue by mre** [emad-elsaid/rubrowser#16]
Tried to reach http://www.emadelsaid.com/rubrowser but it seems I'm entering a redirect loop. Just wanted to let you know.

**Comment by emad-elsaid** [comment]
that's odd, in incognito mode it's working but when I try it in my normal chrome profile it shows this redirect loop issue

**Comment by emad-elsaid** [comment]
anyway you're not missing alot, the webpage is the readme file just rendered as HTML with github pages
