### ISSUE TITLE
Is there a way to generate dependencies around single file

### ISSUE THREAD

**Issue by suchitgupta01** [emad-elsaid/rubrowser#27]
Hi Team,

Is there a way to generate dependencies around single file?

When I try something like  rubrowser /Users/code-name/server/app/controllers/portal/test_controller.rb> output.html
It creates a blank graph.

**Comment by rafaels88** [comment]
it worked for me fine. I could even pass multiple files/folders like `rubrowser file_one.rb my_folder/ another_file.rb > output.html`

**Comment by emad-elsaid** [comment]
@suchitgupta01 I'm guessing it's a machine specific issue as it works for @rafaels88
