### ISSUE TITLE
Mark cyclic dependencies red

### ISSUE THREAD

**Issue by ellcs** [emad-elsaid/rubrowser#3]
I hate dependency cycles. I like to get rid of them. I would like to use rubrowser to find them.
So what about an option to mark cyclic dependencies?

Cheers, ellcs

**Comment by blazeeboy** [comment]
Sure, I will try to work on it as soon as possible

**Comment by blazeeboy** [comment]
Proposed change:
- Backend definition base class should have a method `cyclic?` that tells us if this class is part of cyclic dependencies
- JSON formatter should output this property to the frontend
- Graph should add a class to any node with cyclic attribute = true
- switch that add/remove class to graph to apply red color, 
- css class that paint circles with red if graph has a certain class

**Comment by ellcs** [comment]
Glad to hear that! :+1: 

Which algorithm do you use for the cycle detection? I think there should be something like `strong component detection` in graph theory. 

https://en.wikipedia.org/wiki/Strongly_connected_component#Algorithms

**Comment by blazeeboy** [comment]
I didn't research this part yet, also if there is a gem that already has these algorithms implemented it would be great to utilise it instead of writing the algorithm ourselves

**Comment by ellcs** [comment]
Looks like that there is a algorithm in ruby itself. :gift: 

http://ruby-doc.org/stdlib-2.0.0/libdoc/tsort/rdoc/TSort.html

**Comment by steven-solomon** [comment]
If anyone is interested in pairing on this I would love to make a start on this

**Comment by blazeeboy** [comment]
yes, sure that would be great, maybe we can mark any node that is part of a cyclic dependency with extra attribute.
and lets have the rendering of this attribute to later after we are done with the backend part.
